branch-defaults:
  default:
    environment: sims-master-dev
global:
  application_name: sims-master
  default_ec2_keyname: new
  default_platform: Ruby 2.2 (Passenger Standalone)
  default_region: us-west-1
  profile: eb-cli
  sc: null
